<?php

namespace Database\Seeders;

use App\Models\Account;
use App\Models\AkunLevel1;
use App\Models\AkunLevel2;
use App\Models\AkunLevel3;
use Illuminate\Database\Seeder;

class AccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $akunLevel1 = [];
        $akunLevel2 = [];
        $akunLevel3 = [];
        $akunLevel4 = [];

        $idRekening = 1;
        $rekening = $this->rekening();
        foreach ($rekening as $rek) {
            $kodeAkun = explode('.', $rek['kode']);
            $kodeLevel1 = intval($kodeAkun[0]);
            $kodeLevel2 = intval($kodeAkun[1]);
            $kodeLevel3 = intval($kodeAkun[2]);
            $kodeLevel4 = intval($kodeAkun[3]);

            $rek['created_at'] = now();
            $rek['updated_at'] = now();

            if ($kodeLevel1 > 0 && $kodeLevel2 == 0 && $kodeLevel3 == 0 && $kodeLevel4 == 0) {
                $rek['id'] = $kodeLevel1;
                $akunLevel1[] = $rek;
            }

            if ($kodeLevel1 > 0 && $kodeLevel2 > 0 && $kodeLevel3 == 0 && $kodeLevel4 == 0) {
                $rek['id'] = $kodeLevel1.$kodeLevel2;
                $rek['parent_id'] = $kodeLevel1;
                $akunLevel2[] = $rek;
            }

            if ($kodeLevel1 > 0 && $kodeLevel2 > 0 && $kodeLevel3 > 0 && $kodeLevel4 == 0) {
                $rek['id'] = $kodeLevel1.$kodeLevel2.$kodeLevel3;
                $rek['parent_id'] = $kodeLevel1.$kodeLevel2;
                $akunLevel3[] = $rek;
            }

            if ($kodeLevel1 > 0 && $kodeLevel2 > 0 && $kodeLevel3 > 0 && $kodeLevel4 > 0) {
                $rek['id'] = $idRekening;
                $rek['parent_id'] = $kodeLevel1.$kodeLevel2.$kodeLevel3;
                $akunLevel4[] = $rek;

                $idRekening++;
            }
        }

        AkunLevel1::insert($akunLevel1);
        AkunLevel2::insert($akunLevel2);
        AkunLevel3::insert($akunLevel3);
        Account::insert($akunLevel4);
    }

    private function rekening()
    {
        return [
            [
                'id' => '1',
                'kode' => '1.0.00.00',
                'nama' => 'Aset',
                'parent_id' => '0',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '50',
                'kode' => '2.0.00.00',
                'nama' => 'Utang',
                'parent_id' => '0',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '72',
                'kode' => '3.0.00.00',
                'nama' => 'Modal',
                'parent_id' => '0',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '83',
                'kode' => '4.0.00.00',
                'nama' => 'Pendapatan',
                'parent_id' => '0',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '92',
                'kode' => '5.0.00.00',
                'nama' => 'Harga Pokok Penjulan',
                'parent_id' => '0',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '101',
                'kode' => '6.0.00.00',
                'nama' => 'Beban',
                'parent_id' => '0',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '129',
                'kode' => '7.0.00.00',
                'nama' => 'Pendapatan dan Beban Non Usaha',
                'parent_id' => '0',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '2',
                'kode' => '1.1.00.00',
                'nama' => 'Aset Lancar',
                'parent_id' => '1',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '27',
                'kode' => '1.2.00.00',
                'nama' => 'Aset Tidak Lancar',
                'parent_id' => '1',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '47',
                'kode' => '1.3.00.00',
                'nama' => 'Aset Lain-lain',
                'parent_id' => '1',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '51',
                'kode' => '2.1.00.00',
                'nama' => 'Utang Lancar',
                'parent_id' => '50',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '68',
                'kode' => '2.2.00.00',
                'nama' => 'Utang Jangka Panjang',
                'parent_id' => '50',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '73',
                'kode' => '3.1.00.00',
                'nama' => 'Modal Disetor',
                'parent_id' => '72',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '79',
                'kode' => '3.2.00.00',
                'nama' => 'Modal Laba',
                'parent_id' => '72',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '84',
                'kode' => '4.1.00.00',
                'nama' => 'Pendapatan Usaha',
                'parent_id' => '83',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '93',
                'kode' => '5.1.00.00',
                'nama' => 'Harga Pokok Penjualan',
                'parent_id' => '92',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '102',
                'kode' => '6.1.00.00',
                'nama' => 'Beban Usaha',
                'parent_id' => '101',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '130',
                'kode' => '7.1.00.00',
                'nama' => 'Pendapatan Non Usaha',
                'parent_id' => '129',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '135',
                'kode' => '7.2.00.00',
                'nama' => 'Beban Bunga Utang',
                'parent_id' => '129',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '138',
                'kode' => '7.3.00.00',
                'nama' => 'Beban Non Usaha',
                'parent_id' => '129',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '144',
                'kode' => '7.4.00.00',
                'nama' => 'Beban Pajak',
                'parent_id' => '129',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '3',
                'kode' => '1.1.01.00',
                'nama' => 'Kas',
                'parent_id' => '2',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '10',
                'kode' => '1.1.02.00',
                'nama' => 'Setara Kas',
                'parent_id' => '2',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '12',
                'kode' => '1.1.03.00',
                'nama' => 'Persediaan',
                'parent_id' => '2',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '14',
                'kode' => '1.1.04.00',
                'nama' => 'Piutang',
                'parent_id' => '2',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '18',
                'kode' => '1.1.05.00',
                'nama' => 'Pembayaran dimuka',
                'parent_id' => '2',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '21',
                'kode' => '1.1.06.00',
                'nama' => 'Amortisasi Pembayaran dimuka',
                'parent_id' => '2',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '24',
                'kode' => '1.1.07.00',
                'nama' => 'PPN Dibebankan dimuka',
                'parent_id' => '2',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '28',
                'kode' => '1.2.01.00',
                'nama' => 'Aset Tetap dan Inventaris',
                'parent_id' => '27',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '33',
                'kode' => '1.2.02.00',
                'nama' => 'Penyusutan Aset Tetap dan Inventaris',
                'parent_id' => '27',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '37',
                'kode' => '1.2.03.00',
                'nama' => 'Aset Takberwujud',
                'parent_id' => '27',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '41',
                'kode' => '1.2.04.00',
                'nama' => 'Amortisasi Aset Takberwujud',
                'parent_id' => '27',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '45',
                'kode' => '1.2.05.00',
                'nama' => 'Uang Muka & Konstruksi dalam Proses',
                'parent_id' => '27',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '48',
                'kode' => '1.3.01.00',
                'nama' => 'Aset Lain-lain',
                'parent_id' => '47',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '52',
                'kode' => '2.1.01.00',
                'nama' => 'Utang Operasional',
                'parent_id' => '51',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '57',
                'kode' => '2.1.02.00',
                'nama' => 'Utang Pajak',
                'parent_id' => '51',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '61',
                'kode' => '2.1.03.00',
                'nama' => 'Utang Dividen dan Dana Sosial',
                'parent_id' => '51',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '66',
                'kode' => '2.1.04.00',
                'nama' => 'Utang Lain-lain',
                'parent_id' => '51',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '69',
                'kode' => '2.2.01.00',
                'nama' => 'Utang Jangka Panjang',
                'parent_id' => '68',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '74',
                'kode' => '3.1.01.00',
                'nama' => 'Modal Disetor',
                'parent_id' => '73',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '80',
                'kode' => '3.2.01.00',
                'nama' => 'Laba',
                'parent_id' => '79',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '85',
                'kode' => '4.1.01.00',
                'nama' => 'Pendapatan Usaha',
                'parent_id' => '84',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '94',
                'kode' => '5.1.01.00',
                'nama' => 'Harga Pokok Penjualan',
                'parent_id' => '93',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '103',
                'kode' => '6.1.01.00',
                'nama' => 'Beban Gaji',
                'parent_id' => '101',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '105',
                'kode' => '6.1.02.00',
                'nama' => 'Beban Tunjangan',
                'parent_id' => '102',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '107',
                'kode' => '6.1.03.00',
                'nama' => 'Beban Administrasi dan Umum',
                'parent_id' => '102',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '109',
                'kode' => '6.1.04.00',
                'nama' => 'Beban Pemasaran',
                'parent_id' => '102',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '111',
                'kode' => '6.1.05.00',
                'nama' => 'Beban Transport',
                'parent_id' => '102',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '113',
                'kode' => '6.1.06.00',
                'nama' => 'Beban Training & Rapat',
                'parent_id' => '102',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '115',
                'kode' => '6.1.07.00',
                'nama' => 'Beban Perawatan dan Perbaikan Aset',
                'parent_id' => '102',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '117',
                'kode' => '6.1.08.00',
                'nama' => 'Beban Penyusutan & Amortisasi',
                'parent_id' => '102',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '124',
                'kode' => '6.1.09.00',
                'nama' => 'Beban Penyesuaian Persediaan & Piutang',
                'parent_id' => '102',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '127',
                'kode' => '6.1.10.00',
                'nama' => 'Beban Usaha lain-lain',
                'parent_id' => '102',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '131',
                'kode' => '7.1.01.00',
                'nama' => 'Pendapatan Bunga',
                'parent_id' => '130',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '136',
                'kode' => '7.2.01.00',
                'nama' => 'Beban Bunga Utang',
                'parent_id' => '135',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '139',
                'kode' => '7.3.01.00',
                'nama' => 'Beban Admin & Pajak Bank ',
                'parent_id' => '138',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '142',
                'kode' => '7.3.02.00',
                'nama' => 'Beban Non Usaha Lain-lain',
                'parent_id' => '138',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '145',
                'kode' => '7.4.01.00',
                'nama' => 'Beban Pajak',
                'parent_id' => '144',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '4',
                'kode' => '1.1.01.01',
                'nama' => 'Buku Kas Umum',
                'parent_id' => '3',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '5',
                'kode' => '1.1.01.02',
                'nama' => 'Buku Kas Kecil',
                'parent_id' => '3',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '6',
                'kode' => '1.1.01.03',
                'nama' => 'Bank BRI',
                'parent_id' => '3',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => '7676767',
                'atas_nama_rek' => 'Sumpeno',
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '7',
                'kode' => '1.1.01.04',
                'nama' => 'Bank BNI',
                'parent_id' => '3',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => '666447',
                'atas_nama_rek' => 'Kalimin',
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '8',
                'kode' => '1.1.01.05',
                'nama' => 'Bank Mandiri',
                'parent_id' => '3',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => '2356161',
                'atas_nama_rek' => 'Budi Slamet',
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '9',
                'kode' => '1.1.01.06',
                'nama' => 'Bank BCA',
                'parent_id' => '3',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => '3427162',
                'atas_nama_rek' => 'Sudarmadji',
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '11',
                'kode' => '1.1.02.01',
                'nama' => 'Deposito < 3 bulan',
                'parent_id' => '10',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '13',
                'kode' => '1.1.03.01',
                'nama' => 'Persediaan',
                'parent_id' => '12',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '15',
                'kode' => '1.1.04.01',
                'nama' => 'Piutang Dagang',
                'parent_id' => '14',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '16',
                'kode' => '1.1.04.02',
                'nama' => 'Pitang Karyawan',
                'parent_id' => '14',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '17',
                'kode' => '1.1.04.03',
                'nama' => 'Piutang Lain-lain',
                'parent_id' => '14',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '19',
                'kode' => '1.1.05.01',
                'nama' => 'Sewa dibayar dimuka',
                'parent_id' => '18',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '20',
                'kode' => '1.1.05.02',
                'nama' => 'Pembayaran dimuka lainnya',
                'parent_id' => '18',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '22',
                'kode' => '1.1.06.01',
                'nama' => 'Akumulasi Amortisasi Pembayaran dimuka lainnya',
                'parent_id' => '21',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '23',
                'kode' => '1.1.06.02',
                'nama' => 'Akumulasi Amortisasi Sewa dibayar dimuka',
                'parent_id' => '21',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '25',
                'kode' => '1.1.07.01',
                'nama' => 'PPN Keluaran (Penjualan]',
                'parent_id' => '24',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '26',
                'kode' => '1.1.07.02',
                'nama' => 'PPN Masukan (Pembelian]',
                'parent_id' => '24',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '29',
                'kode' => '1.2.01.01',
                'nama' => 'Tanah',
                'parent_id' => '28',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '30',
                'kode' => '1.2.01.02',
                'nama' => 'Gedung',
                'parent_id' => '28',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '31',
                'kode' => '1.2.01.03',
                'nama' => 'Kendaraan dan Mesin produksi',
                'parent_id' => '28',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '32',
                'kode' => '1.2.01.04',
                'nama' => 'Peralatan umum/ Inventaris',
                'parent_id' => '28',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '34',
                'kode' => '1.2.02.01',
                'nama' => 'Akumulasi Penyusutan Gedung',
                'parent_id' => '33',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '35',
                'kode' => '1.2.02.02',
                'nama' => 'Akumulasi Penyusutan Kendaraan dan Mesin produksi',
                'parent_id' => '33',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '36',
                'kode' => '1.2.02.03',
                'nama' => 'Akumulasi Penyusutan Peralatan umum/ Inventaris',
                'parent_id' => '33',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '38',
                'kode' => '1.2.03.01',
                'nama' => 'Perijinan',
                'parent_id' => '37',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '39',
                'kode' => '1.2.03.02',
                'nama' => 'Lisensi dan Merk',
                'parent_id' => '37',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '40',
                'kode' => '1.2.03.03',
                'nama' => 'Aset Takberwujud Lainnya',
                'parent_id' => '37',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '42',
                'kode' => '1.2.04.01',
                'nama' => 'Akumulasi Amortisasi Perijinan',
                'parent_id' => '41',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '43',
                'kode' => '1.2.04.02',
                'nama' => 'Akumulasi Amortisasi Lisensi dan Merk',
                'parent_id' => '41',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '44',
                'kode' => '1.2.04.03',
                'nama' => 'Akumulasi Amortisasi Takberwujud Lainnya',
                'parent_id' => '41',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '46',
                'kode' => '1.2.05.01',
                'nama' => 'Uang Muka & Konstruksi dalam Proses',
                'parent_id' => '45',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '49',
                'kode' => '1.3.01.01',
                'nama' => 'Aset Lain-lain',
                'parent_id' => '48',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '53',
                'kode' => '2.1.01.01',
                'nama' => 'Utang Pembelian',
                'parent_id' => '52',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '54',
                'kode' => '2.1.01.02',
                'nama' => 'Utang DP',
                'parent_id' => '52',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '55',
                'kode' => '2.1.01.03',
                'nama' => 'Utang Gaji',
                'parent_id' => '52',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '56',
                'kode' => '2.1.01.04',
                'nama' => 'Utang Operasional',
                'parent_id' => '52',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '58',
                'kode' => '2.1.02.01',
                'nama' => 'PPN Masukan (Pembelian]',
                'parent_id' => '57',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '59',
                'kode' => '2.1.02.02',
                'nama' => 'PPN Keluaran (Penjualan]',
                'parent_id' => '57',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '60',
                'kode' => '2.1.02.03',
                'nama' => 'Utang Pajak lainnya',
                'parent_id' => '57',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '62',
                'kode' => '2.1.03.01',
                'nama' => 'Dividen untuk Bumdesma Lkd',
                'parent_id' => '61',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '63',
                'kode' => '2.1.03.02',
                'nama' => 'Dividen untuk Desa',
                'parent_id' => '61',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '64',
                'kode' => '2.1.03.03',
                'nama' => 'Dividen untuk Penyerta Modal Lainnya',
                'parent_id' => '61',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '65',
                'kode' => '2.1.03.04',
                'nama' => 'Alokasi Dana Sosial',
                'parent_id' => '61',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '67',
                'kode' => '2.1.04.01',
                'nama' => 'Utang Jangka Pendek Lain-lain',
                'parent_id' => '66',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '70',
                'kode' => '2.2.01.01',
                'nama' => 'Utang Bank',
                'parent_id' => '69',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '71',
                'kode' => '2.2.01.02',
                'nama' => 'Utang Jangka Panjang Lain-lain',
                'parent_id' => '69',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '75',
                'kode' => '3.1.01.01',
                'nama' => 'Modal Bumdesma Lkd',
                'parent_id' => '74',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '76',
                'kode' => '3.1.01.02',
                'nama' => 'Modal Penyertaan Desa',
                'parent_id' => '74',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '77',
                'kode' => '3.1.01.03',
                'nama' => 'Modal Penyertaan Masyarakat Desa',
                'parent_id' => '74',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '78',
                'kode' => '3.1.01.04',
                'nama' => 'Modal Lain-lain',
                'parent_id' => '74',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '81',
                'kode' => '3.2.01.01',
                'nama' => 'Laba Ditahan',
                'parent_id' => '80',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '82',
                'kode' => '3.2.01.02',
                'nama' => 'Ikhtisar Laba Rugi Berjalan',
                'parent_id' => '80',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '86',
                'kode' => '4.1.01.01',
                'nama' => 'Penjualan',
                'parent_id' => '85',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '87',
                'kode' => '4.1.01.02',
                'nama' => 'Diskon Penjualan',
                'parent_id' => '85',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '88',
                'kode' => '4.1.01.03',
                'nama' => 'Retur Penjualan',
                'parent_id' => '85',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '89',
                'kode' => '4.1.01.04',
                'nama' => 'Pendapatan Sewa Ruang/Rak',
                'parent_id' => '85',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '90',
                'kode' => '4.1.01.05',
                'nama' => 'Pendapatan Lain-lain',
                'parent_id' => '85',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '91',
                'kode' => '4.1.01.06',
                'nama' => 'Cashback Penjualan',
                'parent_id' => '85',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '95',
                'kode' => '5.1.01.01',
                'nama' => 'Beban Pokok Pendapatan',
                'parent_id' => '94',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '96',
                'kode' => '5.1.01.02',
                'nama' => 'Diskon Pembelian',
                'parent_id' => '94',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '97',
                'kode' => '5.1.01.03',
                'nama' => 'Retur Pembelian',
                'parent_id' => '94',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '98',
                'kode' => '5.1.01.04',
                'nama' => 'Beban Produksi',
                'parent_id' => '94',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '99',
                'kode' => '5.1.01.05',
                'nama' => 'Beban Transport Produk',
                'parent_id' => '94',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '100',
                'kode' => '5.1.01.06',
                'nama' => 'Cashback Pembelian',
                'parent_id' => '94',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '104',
                'kode' => '6.1.01.01',
                'nama' => 'Beban Gaji',
                'parent_id' => '103',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '106',
                'kode' => '6.1.02.01',
                'nama' => 'Beban Tunjangan',
                'parent_id' => '105',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '108',
                'kode' => '6.1.03.01',
                'nama' => 'Beban Administrasi dan Umum',
                'parent_id' => '107',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '110',
                'kode' => '6.1.04.01',
                'nama' => 'Beban Promosi & Pemasaran',
                'parent_id' => '109',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '112',
                'kode' => '6.1.05.01',
                'nama' => 'Beban Transport Operasional',
                'parent_id' => '111',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '114',
                'kode' => '6.1.06.01',
                'nama' => 'Beban Training & Rapat',
                'parent_id' => '113',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '116',
                'kode' => '6.1.07.01',
                'nama' => 'Beban Perawatan dan Perbaikan Aset',
                'parent_id' => '115',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '118',
                'kode' => '6.1.08.01',
                'nama' => 'Beban Penyusutan Gedung',
                'parent_id' => '117',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '119',
                'kode' => '6.1.08.02',
                'nama' => 'Beban Penyusutan Kendaraan',
                'parent_id' => '117',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '120',
                'kode' => '6.1.08.03',
                'nama' => 'Beban Penyusutan Peralatan/Inventaris',
                'parent_id' => '117',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '121',
                'kode' => '6.1.08.04',
                'nama' => 'Beban Amortisasi Sewa dibayar dimuka',
                'parent_id' => '117',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '122',
                'kode' => '6.1.08.05',
                'nama' => 'Beban Amortisasi Perijinan',
                'parent_id' => '117',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '123',
                'kode' => '6.1.08.06',
                'nama' => 'Beban Amortisasi Lisensi',
                'parent_id' => '117',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '125',
                'kode' => '6.1.09.01',
                'nama' => 'Laba/rugi Stok Opname Persediaan',
                'parent_id' => '124',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '128',
                'kode' => '6.1.10.01',
                'nama' => 'Beban Usaha Lain-lain',
                'parent_id' => '127',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '132',
                'kode' => '7.1.01.01',
                'nama' => 'Pendapatan Bunga Bank',
                'parent_id' => '131',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '133',
                'kode' => '7.1.01.02',
                'nama' => 'Pendapatan Bunga Deposito',
                'parent_id' => '131',
                'jenis_mutasi' => 'kredit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '137',
                'kode' => '7.2.01.01',
                'nama' => 'Beban Bunga Utang',
                'parent_id' => '136',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '140',
                'kode' => '7.3.01.01',
                'nama' => 'Beban Admin Bank',
                'parent_id' => '139',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '141',
                'kode' => '7.3.01.02',
                'nama' => 'Beban Pajak Bunga Bank',
                'parent_id' => '139',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '143',
                'kode' => '7.3.02.01',
                'nama' => 'Beban Non Usaha Lain-lain',
                'parent_id' => '142',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '146',
                'kode' => '7.4.01.01',
                'nama' => 'Beban PPN Masukan',
                'parent_id' => '145',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
            [
                'id' => '147',
                'kode' => '7.4.01.02',
                'nama' => 'Taksiran PPh',
                'parent_id' => '145',
                'jenis_mutasi' => 'debit',
                'no_rek_bank' => null,
                'atas_nama_rek' => null,
                'created_at' => '2025-04-21 14:08:45',
                'updated_at' => '2025-04-21 14:08:45',
            ],
        ];
    }
}
